name: build

on:
  push:
    #branches: [ main ]
  pull_request:
    #branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # UBUNTU SETUP
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-16 cppcheck

      # WINDOWS SETUP
      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install cppcheck --no-progress
          'C:\Program Files\Cppcheck' >> $env:GITHUB_PATH

      # CONFIGURE (Ubuntu)
      - name: Configure (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-16 -DENABLE_DOXYGEN=OFF

      # CONFIGURE (Windows)
      - name: Configure (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_DOXYGEN=OFF

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Debug
