name: Doxygen + Pages

on:
  push:
    branches: [ main, doxy ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
# cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_CPPCHECK=OFF

      - name: Build Doxygen target
        run: cmake --build build --target doxygen -j 4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/docs/html

  deploy-pages:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/doxy' || github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
